[project]
name = "norkaxt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pygobject>=3.52.3",
    "pygobject-stubs>=2.13.0",
    "ruff>=0.12.0",
]
