[project]
name = "norka"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "humanize>=4.12.3",
    "loguru>=0.7.3",
    "nanoid>=2.0.0",
    "pygobject>=3.52.3",
    "pygobject-stubs>=2.13.0",
    "ruff>=0.12.1",
]
